A0-1243: Change log level of exiting process logs from info to debug
Cardinal-Cryptography/AlephBFT pull request #253
Opened 2022-08-08 11:29 UTC by krzysztofziobro

2022-08-08 12:22 UTC, kostekIV approved these changes

2022-08-09 07:56 UTC, DamianStraszak requested changes
Thanks. You can switch back the `status logs` (in comments) to `INFO` but otherwise it's fine.

How does it look like now in logs when a session changes?

2022-08-09 07:56 UTC, DamianStraszak commented on consensus/src/member.rs
> +        debug!(target: "AlephBFT-member", "{}", status);
This is absolutely crucial log, we cannot turn it off :) 
Note that it is NOT logged on start or end. This is a status log. 

I will leave a few more comments saying "status log", which means they should go back to `INFO`.

2022-08-09 07:56 UTC, DamianStraszak commented on consensus/src/runway/backup.rs
> +    debug!(target: "AlephBFT-unit-backup", "loaded units from backup. Loaded {:?} units", units.len());
status log, `INFO` is fine

2022-08-09 07:56 UTC, DamianStraszak commented on consensus/src/runway/backup.rs
> +    debug!(target: "AlephBFT-unit-backup", "received next round from unit collection: {:?}", next_round_collection);
status log, `INFO` is fine

2022-08-09 07:56 UTC, DamianStraszak commented on consensus/src/runway/collection.rs
> +        debug!(target: "AlephBFT-runway", "Finished initial unit collection with status: {:?}", self.collection.status());
status log, `INFO` is fine

2022-08-09 07:56 UTC, DamianStraszak commented on consensus/src/runway/collection.rs
> +        debug!(target: "AlephBFT-runway", "Initial unit collection status report: status - {:?}, collected starting rounds - {}", self.collection.status(), self.collection.collected_starting_rounds);
status log, `INFO` is fine

2022-08-09 07:56 UTC, DamianStraszak commented on consensus/src/runway/collection.rs
> +                            debug!(target: "AlephBFT-runway", "Finished initial unit collection with status: {:?}", self.collection.status());
status log, `INFO` is fine

2022-08-09 08:08 UTC, krzysztofziobro commented
![info_logs_blockchain](https://user-images.githubusercontent.com/86822080/183598029-2c4b1191-6296-48f6-a06d-8e4beac9f9cb.png)
That's how it looks when running a blockchain example.

2022-08-09 08:27 UTC, DamianStraszak approved these changes
Awesome, this is exactly as I wanted this to look like!

2022-08-09 08:28 UTC, merged